Daniil rubets lab 18 patch
Programming-Classrooms/practicalworks-DaniilRubets pull request #14
Opened 2024-05-23 11:43 UTC by DaniilRubets

## Pull Request лабораторной работы №8

### Условие лабраторной работы

Описать класс Book, имеющий следующие поля:
o ISBN (идентификационный номер) – уникальное текстовое
поле
o title (название книги) – текстовое поле
o authors (коллекция авторов) – каждый автор - текстовое поле
o price (цена) – вещественное значение
o count (количество экземпляров) – целое значение
Описать класс Library, содержащий коллекцию объектов класса Book.
Реализовать следующий функционал:
o Добавить книгу.
o Найти книгу (по идентификационному номеру).
o Удалить книгу (по идентификационному номеру).
o Просмотреть список книг.
o Добавить автора (по идентификационному номеру).
o Удалить автора (по идентификационному номеру).
o Сортировать список книг по идентификационному номеру.
o Сортировать список книг по алфавиту названий.
### Вопросы по условию

Вопросов не имею.

2024-05-25 15:44 UTC, AlexandrOsiptsov requested changes
Неплохо, но можно лучше, работай

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/BUILD
Название модуля кайф конечно, но лучше бы исправить

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.cpp
> +}
Это можно реализовать методом из `stl`

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.cpp
> +}
А лямбду сюда добавить пробовал?

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.cpp
> +    }
Аналогично

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.cpp
> +}
Пустая строка в конце файла

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.hpp
> +#include <algorithm>
Сначала идут системные библиотеки, потом уже самописные, с разделением пустой строкой между двумя частями

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Biblioteca/Library.cpp
Нет комментариев, разделяющий по смыслу модули, читать тяжело

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Book/Book.cpp
> +}
Как-то очень сомнительно. Почему бы просто не хранить число?

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Book/Book.cpp
Разделения комментами нет, читать тяжело

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/Book/Book.hpp
> +#include <iostream>
Пустая строка смысловая

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/tests/LibraryTest.cpp
> +#include "gtest/gtest.h"
Сначала системные, потом свои

2024-05-25 15:44 UTC, AlexandrOsiptsov commented on laboratory-task-18/src/tests/LibraryTest.cpp
Как-то мало тестов, давай ещё

2024-05-25 15:51 UTC, DaniilRubets commented on laboratory-task-18/src/Book/Book.cpp
> +}
Потому что в условии сказано, что одним из поля класса является IBSN номер, т е 13-значный идентификационный номер. Я искал алгоритм его заполнения, но как оказалось эти номера везде заполняются по-разному и единой системы какой-то нет. Поэтому я сделал что-то простенькое наподобие реального IBSN.

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:19 UTC, merged