Лабораторная работа №4
Programming-Classrooms/practicalworks-DaniilRubets pull request #3
Opened 2023-12-03 19:13 UTC by DaniilRubets

## Pull Request лабораторной работы №4

### Условие лабраторной работы

Вариант 8
1.Заполнить квадратную матрицу последовательными натуральными числами, расположенными по спирали, начиная с левого верхнего угла и продвигаясь по часовой стрелке.
2. Найти сумму элементов побочной диагонали.

### Вопросы по условию

Отсутствуют

2024-01-06 20:01 UTC, AlexandrOsiptsov requested changes
Меняй

2024-01-06 20:01 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +    cout << "It is sum of secondary diagonal:" << sum;
В разы логичнее было бы, если бы функция возвращала эту сумму как целочисленное значение, которое потом бы использовалось в main для вывода на экран

2024-01-06 20:01 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
ing в названии. К тому же, ты ставишь ширину вывода, при этом полностью лишая пользователя функции возможности самому её выбирать.

2024-01-06 20:01 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void switchMode(int32_t& value, int32_t& mode)
Логическая ошибка перевода в названии функции

2024-01-12 06:31 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +using std::cout;
Готово! 63a3b2307f3a67ddfd1820675f8ceba20b1d68d1

2024-01-12 06:34 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +}
Исправил! 971ea6b64c9e53fe27996999ed76b663912728d9

2024-01-12 06:48 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +}
Готово! 324564232bc7c099e5e95505d8bf7c4d13d68087

2024-01-12 06:49 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +    for (size_t i = 0; i < rows; i++) {
Префиксное! d470987b430a02e1dde8bf3f8f5741c36a6131d5

2024-01-12 06:49 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +        for (size_t j = 0; j < columns; j++) {
И только ей доверяю я! d470987b430a02e1dde8bf3f8f5741c36a6131d5

2024-01-12 06:53 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +    cout << "It is sum of secondary diagonal:" << sum;
Исправил! 4bef56841d4da4607d4108283c5672d2254b8077

2024-01-12 08:01 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +}
Держи 0b774a0636f754e52f7365e845a7d37baa1fac93

2024-01-12 08:06 UTC, DaniilRubets commented on laboratory-task-4/main.cpp
> +void switchMode(int32_t& value, int32_t& mode)
ЛОВИ! 82c516899820b84439b962a069391a2a7eddf844

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:41 UTC, merged