Лабораторная работа №1
Programming-Classrooms/practicalworks-DaniilRubets pull request #4
Opened 2023-12-03 19:25 UTC by DaniilRubets

## Pull Request лабораторной работы №1

### Условие лабраторной работы
Разработать консольное приложение для вычисления приближённого значения функции, используя представление ее в виде ряда Тейлора. Вычисления заканчивать, когда очередное слагаемое окажется по модулю меньше заданного числа , где  ,  – натуральное число, . Сравнить полученный результат со значением, вычисленным с помощью стандартных функций. Значение  и  ввести по запросу. 
Функция №3.

### Вопросы по условию

Отсутствуют

2023-12-24 12:22 UTC, AlexandrOsiptsov requested changes

2023-12-24 12:22 UTC, AlexandrOsiptsov commented on laboratory-task-1/main.cpp
> +    double term = -x*x/2;
как дела

2023-12-24 12:26 UTC, DaniilRubets commented on laboratory-task-1/main.cpp
> +    double term = -x*x/2;
ой

2023-12-24 12:29 UTC, DaniilRubets commented on laboratory-task-1/main.cpp
> +    double term = -x*x/2;
Исправил 41a7299f95270fcdf6a872ab86cae76b3cb36f52

2024-01-12 21:15 UTC, Voio77 approved these changes
Good Luck

2024-01-12 21:17 UTC, AlexandrOsiptsov approved these changes

2024-01-12 21:18 UTC, merged