Лабораторная работа №9
Programming-Classrooms/practicalworks-DaniilRubets pull request #6
Opened 2023-12-23 22:43 UTC by DaniilRubets

## Pull Request лабораторной работы №9

### Условие лабраторной работы
Задан текстовый файл input.txt. Требуется определить строки этого  файла, содержащие максимальную по длине подстроку, состоящую из  одинаковых символов русского алфавита. Заглавные и строчные буквы не 
различаются. Если таких строк несколько, найти первые 10. Результат  вывести на консоль в форме, удобной для чтения.  

### Вопросы по условию
Вопросы отсутствуют.

2024-01-06 18:13 UTC, AlexandrOsiptsov requested changes
Исправь прокомментированные моменты

2024-01-06 18:13 UTC, AlexandrOsiptsov commented on laboratory-task-9/main.cpp
> +}
Название так себе

2024-01-06 18:13 UTC, AlexandrOsiptsov commented on laboratory-task-9/main.cpp
> +void searchMaxSubstring(std::fstream& file, std::string& line)
По-хорошему функция должна возвращать maxSubstring, а не искать и выводить в консоль

2024-01-06 21:01 UTC, DaniilRubets commented on laboratory-task-9/main.cpp
> +}
Show must go on!cec19f3fabf4baffa7a12b63cae941551c0148c0

2024-01-06 21:01 UTC, DaniilRubets commented on laboratory-task-9/main.cpp
> +}
Show must go on! cec19f3fabf4baffa7a12b63cae941551c0148c0

2024-01-06 21:02 UTC, DaniilRubets commented on laboratory-task-9/main.cpp
> +void searchMaxSubstring(std::fstream& file, std::string& line)
Могилев - это город самый лучший! Могилев, он нас всему научит! (pov: все исправил) cec19f3fabf4baffa7a12b63cae941551c0148c0

2024-01-12 21:37 UTC, Voio77 approved these changes
Good Luck

2024-01-12 21:38 UTC, AlexandrOsiptsov approved these changes
Могилёв - самый лучший город!

2024-01-12 21:44 UTC, AlexandrOsiptsov commented on laboratory-task-9/main.cpp
> +void searchMaxSubstring(std::fstream& file, std::string& line)
> Могилев - это город самый лучший! Могилев, он нас всему научит! (pov: все исправил) [cec19f3](https://github.com/Programming-Classrooms/practicalworks-DaniilRubets/commit/cec19f3fabf4baffa7a12b63cae941551c0148c0)

10 баллов за экзамен автоматом

2024-01-12 21:44 UTC, merged