Лабораторная работа №8
Programming-Classrooms/practicalworks-DaniilRubets pull request #7
Opened 2023-12-24 10:45 UTC by DaniilRubets

## Pull Request лабораторной работы №8

### Условие лабраторной работы

Строка состоит из слов, разделённых знаками препинания. За один просмотр символов строки найти все слова, содержащие наибольшее количество различных символов, и занести их в новую строку. Слова в новой строке должны разделяться ровно одним пробелом. Решение задачи получить за один просмотр символов строки.
### Вопросы по условию
Вопросы отсутствуют.

2024-01-06 18:18 UTC, AlexandrOsiptsov requested changes

2024-01-06 18:18 UTC, AlexandrOsiptsov commented on laboratory-task-8/main.cpp
> + }
Функция должна выполнять одно действие

2024-01-06 18:18 UTC, AlexandrOsiptsov commented on laboratory-task-8/main.cpp
> +}
Опять же, логика как и в 9-ой лабе. Лучше возвращать это как какой-то объект, а потом уже выводить на экран или другой функцией или просто циклом в main

2024-01-06 18:18 UTC, AlexandrOsiptsov commented on laboratory-task-8/main.cpp
> +      return 0;
Проверь отступ

2024-01-06 20:49 UTC, DaniilRubets commented on laboratory-task-8/main.cpp
> + }
Исправил 2f6ceefc8a01ac7a142813376be07816dc53890b

2024-01-06 20:50 UTC, DaniilRubets commented on laboratory-task-8/main.cpp
> +}
Если к дверям не подходят ключи, вышиби дверь плечом 2f6ceefc8a01ac7a142813376be07816dc53890b

2024-01-06 20:50 UTC, DaniilRubets commented on laboratory-task-8/main.cpp
> +      return 0;
Восьмиклассница вернулась домой с пустынной улицы 2f6ceefc8a01ac7a142813376be07816dc53890b

2024-01-14 21:27 UTC, AlexandrOsiptsov approved these changes

2024-01-14 21:29 UTC, merged